[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Headers = "*"
Access-Control-Allow-Methods = "OPTIONS, GET"
Access-Control-Allow-Origin = "*"
Access-Control-Max-Age = "3600"
Access-Control-Request-Method = "*"
Cache-Control = "max-age=86400"